.TH simple_shell 1
.SH NAME
.B main.h
- simple shell
.SH SYNOPSIS
A basic UNIX command line interpreter
.SH DESCRIPTION
Displays prompt whilst awaiting a command from user. The command is then interpreted and the prompts are displayed each time the command is being executed.

.SH USAGE
All files are to be compiled on the Ubuntu 14.04 LTS machine with "gcc -Wall -Werror -Wextra -pedantic -std=gnu89"

To start programme, run:
.br
/# ./main.c

.B env -
Prints the current enviroment

.SH RETURN VALUE
simple_shell will exit with status 0 unless status is specified.

.SH AUTHORS
Tiana Govender, Ikenna Ezeanyaeji
